[ayucloud.services]
email  kzfbanr355@qabq.com
last_checkin  2025-05-07 10:14:23.081205+08:00
node_n  99
sub_info  0B  0B  2025-05-08 10:14:22+08:00  (剩余 0B -12 days, 23:53:10.340782)
sub_url  https://network.ayucloud.nl/link/FSPFi6FQyhYNlshV?clash=1
time  2025-05-07 10:14:24.071939+08:00
保存base64订阅失败  no base64
保存clash订阅失败  mapping values are not allowed here in "<byte string>", line 2, column 270: ... Q==" lang="en" style="background: #2B2B2B;"> ^ (line: 2)
保存订阅信息失败  no sub info
尝试签到失败  HTTPSConnectionPool(host='ayucloud.services', port=443): Max retries exceeded with url: /user/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f22a179d4e0>, 'Connection to ayucloud.services timed out. (connect timeout=5)'))
更新订阅链接/续费续签失败  注册失败(fysavup207@gmail.com): HTTPSConnectionPool(host='ayucloud.services', port=443): Max retries exceeded with url: /user/register (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f22a1636b60>, 'Connection to ayucloud.services timed out. (connect timeout=5)'))
